baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'C# Web Development'
theme = "hugo-theme-relearn"

canonifyURLs = false

[params]
  themeVariant = ["lc-light", "lc-dark-blue", "lc-dark-blue-two"]
