baseURL = 'https://csharp-web-dev-curriculum.netlify.app'
languageCode = 'en-us'
title = 'C# Web Development'
theme = "hugo-theme-relearn"

canonifyURLs = false

[params]
  themeVariant = ["lc-light", "lc-dark-blue", "lc-dark-blue-two"]
